### ISSUE TITLE
About Section 3.1. Ranking Positive Edge Pixels over Negatives in paper

### ISSUE THREAD

**Issue by Ozone-oo** [Bedrettin-Cetinkaya/RankED#1]
I've been working on replicating the findings from your paper, "RankED: Addressing Imbalance and Uncertainty in Edge Detection Using Ranking-based Losses", specifically the method described in "Section 3.1. Ranking Positive Edge Pixels over Negatives". I've hit some roadblocks and would greatly appreciate if you could release the code pertaining to this section.

Thank you for considering my request. I'm open to any further dialogue and ready to adhere to any terms you might set for sharing the code.

**Comment by Bedrettin-Cetinkaya** [comment]
Thank you for your interest. I will share code and pretrained models asap.

**Comment by Bedrettin-Cetinkaya** [comment]
I added neccessary files for training & inference. Evaluation code and our pretrained model will be uploaded asap.
