### ISSUE TITLE
About the definition of CP function in equation 13

### ISSUE THREAD

**Issue by meetviolet** [Bedrettin-Cetinkaya/RankED#4]
Hi, what's the exact definition of CP function in equation 13? I didn't find any clue in paper [1,14]. Did I miss sth.?

**Comment by Bedrettin-Cetinkaya** [comment]
hello, CP stands for correspond_pixels which is used in evaluation. You can find python version of this function [here](https://github.com/Walstruzz/edge_eval_python/blob/main/impl/correspond_pixels.py) .

**Comment by meetviolet** [comment]
Thx~~
