### ISSUE TITLE
Could you tell me the number of parameters that RANKED needs to learn

### ISSUE THREAD

**Issue by Star-xing1** [Bedrettin-Cetinkaya/RankED#7]
Sorry to bother you, but due to environmental configuration issues, we are temporarily unable to run your code.

**Comment by Li-yachuan** [comment]
I also didn't run the provided code successfully; MMCV is a bit harsh on the environment. But I avoided MMCV by manually stitching modules into a model based on the config files. The model size is 119.978M, I hope this can help you.

**Comment by Bedrettin-Cetinkaya** [comment]
Hello, sorry for the late reply. The model consists of a base model of swin transformer and uperNet. It has ~121M parameters.
